/**
 * Per-host envelopes for the canonical guidance body.
 *
 * Two write shapes, both idempotent and reversible:
 * - guarded block (upsertBlock / removeBlock): used inside files that also
 *   carry human content (AGENTS.md, CLAUDE.md, rule files). Everything between
 *   the markers is managed and replaced wholesale; everything outside is
 *   preserved.
 * - whole-file managed (writeManagedFile): used for SKILL.md targets which are
 *   generated end-to-end. Refuses to clobber a file that was not created by
 *   `kanbn-mcp setup`.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { renderCanonical, renderSkill } from "./guidance.js";
import { HostSlug, SetupAnswers, WrittenTarget } from "./types.js";

export const BLOCK_START = "<!-- kanbn:start -->";
export const BLOCK_END = "<!-- kanbn:end -->";

/** Marker every whole-file managed target carries so re-runs / uninstall can
 * tell "ours" from "user-authored" without guessing. */
export const FILE_MARKER = "<!-- generated by kanbn-mcp setup; re-run `kanbn-mcp setup` to regenerate, `kanbn-mcp uninstall` to remove -->";

const BLOCK_FOOTER = `This section is managed by kanbn-mcp setup. Re-run \`kanbn-mcp setup\` to regenerate it, or \`kanbn-mcp uninstall\` to remove it. Edits between the markers are overwritten.`;

export function renderBlock(body: string, title?: string): string {
    const heading = title ? `${title}\n\n` : "";
    return `${BLOCK_START}\n${heading}${body.trim()}\n\n${BLOCK_FOOTER}\n${BLOCK_END}`;
}

/**
 * Insert or replace the managed block in a file, preserving all content
 * outside the markers.
 * @param filePath Target file
 * @param block Rendered block (must start with BLOCK_START and end with BLOCK_END)
 * @returns Whether anything was written
 */
export function upsertBlock(filePath: string, block: string): boolean {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
    const startIdx = existing.indexOf(BLOCK_START);
    const endIdx = existing.indexOf(BLOCK_END);
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
        const updated = existing.slice(0, startIdx) + block + existing.slice(endIdx + BLOCK_END.length);
        if (updated !== existing) {
            fs.writeFileSync(filePath, updated);
            return true;
        }
        return false;
    }
    const glue = existing.length === 0
        ? ""
        : existing.endsWith("\n")
            ? (existing.endsWith("\n\n") ? "" : "\n")
            : "\n\n";
    fs.writeFileSync(filePath, existing + glue + block + "\n");
    return true;
}

/**
 * Remove the managed block from a file. Deletes the file when the block was
 * its only content.
 * @param filePath Target file
 * @returns Whether a block was found and removed
 */
export function removeBlock(filePath: string): boolean {
    if (!fs.existsSync(filePath)) {
        return false;
    }
    const existing = fs.readFileSync(filePath, "utf8");
    const startIdx = existing.indexOf(BLOCK_START);
    const endIdx = existing.indexOf(BLOCK_END);
    if (startIdx === -1 || endIdx === -1) {
        return false;
    }
    const remaining = existing.slice(0, startIdx) + existing.slice(endIdx + BLOCK_END.length);
    const cleaned = remaining.replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "").replace(/\n+$/, "") + "\n";
    if (cleaned.trim().length === 0) {
        fs.rmSync(filePath, { force: true });
    } else {
        fs.writeFileSync(filePath, cleaned);
    }
    return true;
}

/**
 * Write a whole-file managed target (SKILL.md). Refuses to overwrite a file
 * that does not carry the managed marker.
 * @param filePath Target file
 * @param content Full file content
 * @returns Whether anything was written
 */
export function writeManagedFile(filePath: string, content: string): boolean {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    if (fs.existsSync(filePath)) {
        const existing = fs.readFileSync(filePath, "utf8");
        if (!existing.includes(FILE_MARKER)) {
            throw new Error(
                `Refusing to overwrite ${filePath}: it exists and was not generated by kanbn-mcp setup. ` +
                `Move it aside, or run \`kanbn-mcp uninstall\` if kanbn-mcp setup wrote it previously.`
            );
        }
        if (existing === content) {
            return false;
        }
    }
    fs.writeFileSync(filePath, content);
    return true;
}

/** Which repo targets each host slug owns. "universal" is AGENTS.md. */
const HOST_REPO_TARGETS: Record<HostSlug, string[]> = {
    opencode: ["universal", "opencode"],
    claude: ["claude"],
    windsurf: ["windsurf"],
    cline: ["cline", "cline-skill"],
    devin: ["universal", "devin"],
    // GitHub Copilot (VS Code) reads AGENTS.md from the workspace root
    // (universal) plus its workspace skill at .github/skills/kanbn/SKILL.md.
    copilot: ["universal", "copilot-skill"],
};

export interface RepoTarget {
    id: string;
    host: string;
    file: string;
    write: (root: string, answers: SetupAnswers) => boolean;
}

export function repoTargets(): RepoTarget[] {
    return [
        {
            id: "universal",
            host: "universal",
            file: "AGENTS.md",
            write: (root, answers) =>
                upsertBlock(
                    path.join(root, "AGENTS.md"),
                    renderBlock(renderCanonical(answers))
                ),
        },
        {
            id: "opencode",
            host: "opencode",
            file: ".opencode/skills/kanbn/SKILL.md",
            write: (root, answers) => writeManagedFile(path.join(root, ".opencode", "skills", "kanbn", "SKILL.md"), renderSkill(answers)),
        },
        {
            id: "claude",
            host: "claude",
            file: "CLAUDE.md",
            write: (root, answers) =>
                upsertBlock(
                    path.join(root, "CLAUDE.md"),
                    renderBlock(renderCanonical(answers))
                ),
        },
        {
            id: "windsurf",
            host: "windsurf",
            file: ".windsurf/rules/kanbn.md",
            write: (root, answers) =>
                upsertBlock(
                    path.join(root, ".windsurf", "rules", "kanbn.md"),
                    renderBlock(renderCanonical(answers))
                ),
        },
        {
            id: "cline",
            host: "cline",
            file: ".clinerules/kanbn.md",
            write: (root, answers) =>
                upsertBlock(
                    path.join(root, ".clinerules", "kanbn.md"),
                    renderBlock(renderCanonical(answers))
                ),
        },
        {
            // Cline's recommended project skill location (docs: .cline/skills/).
            // Kept alongside the .clinerules/kanbn.md rules file: rules are
            // always injected, the skill is auto-triggered by description.
            id: "cline-skill",
            host: "cline",
            file: ".cline/skills/kanbn/SKILL.md",
            write: (root, answers) => writeManagedFile(path.join(root, ".cline", "skills", "kanbn", "SKILL.md"), renderSkill(answers)),
        },
        {
            id: "devin",
            host: "devin",
            file: "skills/kanbn/SKILL.md",
            write: (root, answers) => writeManagedFile(path.join(root, "skills", "kanbn", "SKILL.md"), renderSkill(answers)),
        },
        {
            // Copilot's workspace skill location (SDK: "Project: .github/skills/,
            // .agents/skills/, or .claude/skills/"). Skilled alongside the universal
            // AGENTS.md, which Copilot reads always-on at the workspace root.
            id: "copilot-skill",
            host: "copilot",
            file: ".github/skills/kanbn/SKILL.md",
            write: (root, answers) => writeManagedFile(path.join(root, ".github", "skills", "kanbn", "SKILL.md"), renderSkill(answers)),
        },
    ];
}

export interface EmitPlan {
    targets: WrittenTarget[];
    errors: string[];
}

/**
 * Which host slugs to emit for. `null`/undefined means all repo targets.
 * @param hostFilter Comma-separated host slugs or undefined
 */
export function resolveHostSlugs(hostFilter: string | undefined): HostSlug[] | null {
    if (!hostFilter) {
        return null;
    }
    const slugs = hostFilter.split(",").map((s) => s.trim().toLowerCase());
    for (const slug of slugs) {
        if (!["opencode", "claude", "windsurf", "cline", "devin", "copilot"].includes(slug)) {
            throw new Error(`Unknown host "${slug}". Known hosts: opencode, claude, windsurf, cline, devin, copilot.`);
        }
    }
    return slugs as HostSlug[];
}

/**
 * Compute the planned repo-file writes for a root, filtered by host slugs.
 * @param root Board root directory
 * @param answers Setup answers
 * @param hostSlugs Hosts to emit, or null for all
 * @returns The planned targets (path + host + kind)
 */
export function planRepoEmit(root: string, answers: SetupAnswers, hostSlugs: HostSlug[] | null): EmitPlan {
    const plan: EmitPlan = { targets: [], errors: [] };
    for (const target of repoTargets()) {
        const include = hostSlugs === null || hostSlugs.some((slug) => HOST_REPO_TARGETS[slug]?.includes(target.id) ?? false);
        if (!include) {
            continue;
        }
        plan.targets.push({
            path: path.join(root, target.file),
            host: target.host,
            kind: target.id === "universal" ? "block" : target.file.endsWith("SKILL.md") ? "file" : "block",
            changed: true,
        });
    }
    return plan;
}

/**
 * Apply the planned repo emits. Records every target in scope regardless of
 * whether this run changed it, so the manifest always knows the full managed
 * set (needed by uninstall after unchanged re-runs).
 * @param root Board root directory
 * @param answers Setup answers
 * @param hostSlugs Hosts to emit, or null for all
 * @returns The targets in scope, post-write
 */
export function applyRepoEmit(root: string, answers: SetupAnswers, hostSlugs: HostSlug[] | null): WrittenTarget[] {
    const written: WrittenTarget[] = [];
    for (const target of repoTargets()) {
        const include = hostSlugs === null || hostSlugs.some((slug) => HOST_REPO_TARGETS[slug]?.includes(target.id) ?? false);
        if (!include) {
            continue;
        }
        const changed = target.write(root, answers);
        written.push({
            path: path.join(root, target.file),
            host: target.host,
            kind: target.id === "universal" ? "block" : target.file.endsWith("SKILL.md") ? "file" : "block",
            changed,
        });
    }
    return written;
}